server:
  port: 8080

#ArtemisMQ
spring:
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa

# for example purposes of Camel version 2.18 and below
baeldung:
  api:
    path: '/camel' 
# what to say
greeting: Hello World

# how often to trigger the timer
timer:
  period: 2000

camel:
  springboot:
    # The Camel context name
    name: ServicesRest

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

# The application configuration properties
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s